#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
clear;
#echo "Deleting existing iOS directory...";
#sudo rm -r ios;
echo "Starting Expo prebuild...";
expo prebuild;
if [ $? -ne 0 ]; then
    echo "${RED}Prebuild failed!";
else
    echo "${GREEN}Prebuild succeeded!";
    echo "Building the application for IOS...";
    eas build --profile production --platform ios --local
fi
