#!/bin/bash
clear;
#Sources the email provider environment variables
source ./sendgrid.env;
#Builds the server
printf "\n\nBuilding the server binary...";
go build -o main .;
printf "\n\n";
#Runs the server
printf "\n\nRunning the server binary...";
./main;
