#!/bin/bash
clear;
#Sources the email provider environment variables
source ./sendgrid.env;
#Builds the server
echo "Building the server binary...";
go build -o main .
if [ $? -ne 0 ]; then
    echo "Build failed!"
else
    echo "Build succeeded!"

    #Runs the server
    echo "Running the server binary...";
    ./main;

fi
